config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'frontpage#index'
  get 'top/' => 'frontpage#top'
  get 'new/' => 'frontpage#new'
  get 'rising/' => 'frontpage#rising'
  get 'controversial/' => 'frontpage#controversial'

  resources :subgeddits

  resources :posts
  post 'posts/:id/upvote' => 'posts#upvote'
  post 'posts/:id/downvote' => 'posts#downvote'

  resources :users

end

app/models/comment.rb
class Comment < ActiveRecord::Base
    belongs_to :user
    belongs_to :post
    belongs_to :comment

    def score
        upvotes - downvotes
    end
end

app/models/post.rb
class Post < ActiveRecord::Base
    
    belongs_to :user
    belongs_to :subgeddit

    validates :title, length: { maximum: 300 }
    validates :text, length: { maximum: 15000 }
    validates :link, presence: true

    before_validation(on: :create) do 
        self.slug = title.parameterize("_")

        logger.info "link before: #{link}"

        if link.to_s == ""
            self.link = pretty_link
        end

        logger.info "link after: #{link}"
    end

    # Override for route helper methods (link_to, user_path)
    def to_param
        slug
    end

    def score
        upvotes - downvotes
    end

end

app/models/subgeddit.rb
class Subgeddit < ActiveRecord::Base

    belongs_to :user
    has_many :posts

    validates :name, presence: true, length: { minimum: 3 }
    validates :user, presence: true

    def to_param
        name
    end

    def link_text
        "/g/#{name}"
    end

    def to_s
        link_text
    end
end

app/models/user.rb
class User < ActiveRecord::Base
    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable and :omniauthable
    devise :database_authenticatable, :registerable,
           :recoverable, :rememberable, :trackable, :validatable

    has_many :posts
    has_many :comments
    has_many :subgeddits

    def to_param
        username
    end

    def link_text
        "/u/#{username}"
    end

    def to_s
        username
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/frontpage_controller.rb
class FrontpageController < ApplicationController

    def index
        # need some kind of algorithm here
        @posts = Post.all
    end

    def top
        @posts = Post.all.sort_by { |x| -x.score }
        render 'index'
    end

    def new
        @posts = Post.all.order(created_at: :desc)
        render 'index'
    end

    def rising
        @posts = Post.all
        render 'index'
    end

    def controversial
        @posts = Post.all.sort_by { |x| x.score }
        render 'index'
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

    before_filter :authenticate_user!, only: [:new]

    def index
        @posts = Post.all.sort_by { |post| post.score }.reverse
    end

    def show
        if Post.find_by(id: params[:id]) != nil
            @post = Post.find_by(id: params[:id])
        elsif Post.find_by(slug: params[:id]) != nil
            @post = Post.find_by(slug: params[:id])
        end
        @subgeddit = @post.subgeddit
    end

    def new
        @post = Post.new
    end

    def create
        @post = Post.new(params[:post].permit(:title, :link, :text))
        @post.upvotes = @post.downvotes = 0
        @post.user = current_user
        #<temp>
        @post.subgeddit = Subgeddit.first
        #</temp>
        if @post.save
            redirect_to @post.pretty_link
        else
            render 'new'
        end
    end

    def upvote
        if signed_in?
            logger.info "current upvotes: #{Post.find(params[:id]).upvotes}"
            post = Post.find(params[:id])
            logger.info "upvoting..."
            post.upvotes += 1
            logger.info "new upvotes: #{post.upvotes}"
            post.save
            logger.info "saving..."
        end
    end

    def downvote
        if signed_in?
            logger.info "current upvotes: #{Post.find(params[:id]).upvotes}"
            post = Post.find(params[:id])
            logger.info "upvoting..."
            post.downvotes += 1
            logger.info "new upvotes: #{post.upvotes}"
            post.save
            logger.info "saving..."
        end
    end
end

app/controllers/subgeddits_controller.rb
class SubgedditsController < ApplicationController

    def index
        @subgeddits = Subgeddit.all.order(:name)
    end

    def show
        if Subgeddit.all.find_by(id: params[:id]) != nil
            @subgeddit = Subgeddit.all.find_by(id: params[:id])
        elsif Subgeddit.all.find_by(name: params[:id]) != nil
            @subgeddit = Subgeddit.all.find_by(name: params[:id])
        end

        @posts = @subgeddit.posts
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def index

    end

    def show
        if User.find_by(id: params[:id]) != nil
            @user = User.find_by(id: params[:id])
        elsif User.find_by(username: params[:id]) != nil
            @user = User.find_by(username: params[:id])
        end
        @posts = @user.posts
        @comments = @user.comments
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

    def active(mod)
        mod == params[:action] && controller_name == "frontpage" ? 'class=active' : ''
    end
end

app/helpers/frontpage_helper.rb
module FrontpageHelper

    def get_ad
        ad_images[rand(ad_images.length)]
    end     

    def ad_images
        [
            'http://i1.cpcache.com/product_zoom/776763884/cute_cartoon_monkey_picture_frame.jpg?height=250&width=250&padToSquare=true',
            'http://cg3dmodels.com/wp-content/uploads/2012/05/optimus-prime-transformer-3d-model-250x250.jpg'
        ]
    end
end

app/helpers/posts_helper.rb
module PostsHelper

    def score_string(post)
        "(#{post.upvotes}, #{post.downvotes})"
    end
end

app/helpers/subgeddits_helper.rb
module SubgedditsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/frontpage/index.html.erb
<div id="post_list">
    <% @posts.each_with_index do |post, index| %>
        <%= render partial: 'posts/list_item', locals: {post: post, index: index} %>
    <% end %>
</div>

app/views/layouts/_banner.html.erb
<div id="banner">
    <div id="header">
        <% if user_signed_in? %>
            Signed in as <%= link_to current_user, current_user %>. <%= link_to 'logout', destroy_user_session_path, method: :delete %>
        <% else %>
            You are not signed in.
        <% end %>
    </div>
    <span id="logo">
        <%= link_to image_tag('general/geddit_logo_small.png'), root_path %>
    </span>
    <% if @subgeddit %>
        <span id="subgeddit_link">
            <%= link_to @subgeddit.name.upcase, @subgeddit %>
        </span>
    <% end %>
    <ul>
        <a href="/"><li id="hot" <%= active 'index' %>>hot</li></a>
        <a href="/top"><li id="top" <%= active 'top' %>>top</li></a>
        <a href="/new"><li id="new" <%= active 'new' %>>new</li></a>
        <a href="/rising"><li id="rising" <%= active 'rising' %>>rising</li></a>
        <a href="/controversial"><li id="controversial" <%= active 'controversial' %>>controversial</li></a>
    </ul>
</div>

app/views/layouts/_sidebar.html.erb
<!-- Login box -->
<% if !user_signed_in? %>
<div id="login_box">
    <%= form_for(:user, url: session_path(:user)) do |f| %>
        <%= f.text_field :email, placeholder: 'email' %>
        <%= f.password_field :password, placeholder: 'password' %>
        <%= f.submit 'login' %>
    <% end %> 
</div>
<% end %>

<!-- Ad -->
<a href="http://example.com"><img src="<%= get_ad %>" style="height:250px; width:250px;"/></a>

<!-- new post links -->
<a href="/posts/new" class="new_post_link"><div class="new_post_link">Submit a link</div></a>

<!-- subgeddit-specific content -->
<!--<%= yield :subgeddit_sidebar_block %>-->

<% if @subgeddit %>
    <div id="subgeddit_sidebar_content">
            <%= @subgeddit.description %>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>geddit: the front page of gio's internet</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <%= render partial: 'layouts/banner' %>
    <div id="sidebar">
        <%= render 'layouts/sidebar' %>
    </div>
    <div id="content" role="main">
        <%= yield %>
    </div>
   
</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
    <div class="form_item">
        <div>
            <span id="post_title_label">title</span>
            <span id="title_char_count">0/300</span>
        </div>
        <%= f.text_area :title, rows:2, cols:50 %>
    </div>
    <div class="form_item">
        <span id="post_link_label">link</span>
        <%= f.text_field :link, size:47 %>
    </div>
    <div class="form_item">
        <div>
            <span id="post_text_label">text</span>
            <span id="text_char_count">0/15000</span>
        </div>
        <%= f.text_area :text, rows:3, cols:50 %>
    </div>
    <div>
        <%= f.submit 'submit' %>
    </div>
<% end %>

app/views/posts/_list_item.html.erb
<div class="post_list_item">
<div class="post_list_item_scorediv">
    <div class="post_list_item_scorediv_row1">
        <%= link_to(image_tag('general/up.png', height:"15", width:"15", class:"upvote"), "\#") %>
    </div>
    <div class="post_list_item_scorediv_row2">
        <span class="score"><%= post.score %></span>
    </div>
    <div class="post_list_item_scorediv_row2">
        <%= link_to(image_tag('general/down.png', height:"15", width:"15", class:"downvote"), "\#") %>
    </div>
</div>
<div class="post_list_item_contentdiv">
<p class="post_list_item_row1"><%= link_to post.title, post.link %> <%= score_string(post) %> <span class="post_list_item_user">submitted <%= time_ago_in_words post.created_at %> ago by <%= link_to post.user, post.user %> </span><span class="post_list_item_sub">to <%= link_to post.subgeddit.link_text, post.subgeddit %></span></p>
<p class="post_list_item_row2"><%= link_to "comments", post %></p>
</div>
</div>

app/views/posts/index.html.erb
posts index page

<% @posts.each do |post| %>
    <p><%= link_to post.title, post %> <%= score_string(post) %></p>
<% end %>

app/views/posts/new.html.erb
<div id="form_container">
    <h1>submit to geddit</h1>

    <%= render 'form' %>
</div>

app/views/posts/show.html.erb
<div id="post">
    <div id="post_header">
        <%= render partial: 'posts/list_item', locals: {post: @post} %>
        <p id="post_text"><%= @post.text %></p>
    </div>
    
</div>

app/views/subgeddits/index.html.erb
<ul>
    <% @subgeddits.each do |sub| %>
    <li><%= link_to sub, sub %></li>
    <% end %>
</ul>

app/views/subgeddits/show.html.erb
<div id="post_list">
    <% @posts.each_with_index do |post, index| %>
        <%= render partial: 'posts/list_item', locals: {post: post, index: index} %>
    <% end %>
</div>

<% content_for(:subgeddit_sidebar_block) do %>
    <div id="subgeddit_sidebar_content">
        <%= @subgeddit.description %>
    </div>
<% end %>

app/views/users/index.html.erb
users index page